# Change these first
owner: CoopPlayzz # Your GitHub organization or username, where this repository lives
repo: CoopWebsitesUptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: GitHub
    url: https://github.com/
  - name: Roblox
    url: https://www.roblox.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /CoopWebsitesUptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Website Status
  introTitle: "**Coop** websites status"
  introMessage: this is coops website downtime thing
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
